## **Deep learning - Train Perceptron on IRIS Dataset**


By - Devanshee Gupta (25P02F1001) \
Date - 02/02/2026

#### **1. Importing libraries**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

### **Part A**

---

#### **Loading Dataset**

In [ ]:
df = load_iris()

In [ ]:
iris_df = pd.DataFrame(df.data, columns=df.feature_names)
iris_df['target'] = df.target

display(iris_df.head())

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
iris_df = iris_df[iris_df['target'].isin([0, 1])]
iris_df['target'].value_counts()

target
0    50
1    50
Name: count, dtype: int64

In [ ]:
print("shape of X", iris_df.shape)

shape of X (100, 5)

In [ ]:
iris_df_X = iris_df[['sepal length (cm)','sepal width (cm)']]
iris_df_Y = iris_df['target']

In [ ]:
display(iris_df_X.head())

   sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1
4                5.0               3.6

In [ ]:
display(iris_df_Y.head())

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [ ]:
iris_df_Y = np.where(iris_df_Y == 0, 1, -1)

#### **Train/Test Split**

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(iris_df_X,iris_df_Y,train_size=0.8,random_state=42)
print("shape of X-train", X_train.shape)
print("shape of Y-train", Y_train.shape)
print("shape of X-test", X_test.shape)
print("shape of Y-test", Y_test.shape)

shape of X-train (80, 2)
shape of Y-train (80,)
shape of X-test (20, 2)
shape of Y-test (20,)

#### **Single Layer Perceptron**

In [ ]:
perceptron_model = Perceptron(eta0=0.1, max_iter=100, random_state=0)

In [ ]:
perceptron_model.fit(X_train, Y_train)
Y_pred = perceptron_model.predict(X_test)

In [ ]:
X_train_pred = perceptron_model.predict(X_train)

In [ ]:
training_accuracy = accuracy_score(Y_train, X_train_pred)
print(f"Training Accuracy: {training_accuracy:.2f}")
testing_accuracy = accuracy_score(Y_test, Y_pred)
print(f"Testing Accuracy: {testing_accuracy:.2f}")

Training Accuracy: 0.96
Testing Accuracy: 1.00

In [ ]:
print(f"Coefficients (Weights): {perceptron_model.coef_}")
print(f"Intercept (Bias): {perceptron_model.intercept_}")

Coefficients (Weights): [[-2.82  4.8 ]]
Intercept (Bias): [1.]

In [ ]:
class_report = classification_report(Y_test, Y_pred)
print("Classification Report:\n", class_report)

Classification Report:
               precision    recall  f1-score   support

          -1       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20